name: resolver

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "resolver.py"
      - "requirements.txt"
      - ".github/workflows/resolver.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    container:
      image: python:3.11-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements (if present)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Run resolver
        run: python resolver.py
